---
vmalert_container_name: vmalert
vmalert_docker_image: "victoriametrics/vmalert:v1.113.0"
vmalert_docker_network_name: prom_network
vmalert_config_dir: /var/lib/vmalert
vmalert_ports: []
vmalert_command:
  # vmselect or balancer
  - '--datasource.url=http://{{ vmselect_container_name }}:8481/select/0/prometheus'
  - '--remoteRead.url=http://{{ vmselect_container_name }}:8481/select/0/prometheus'
  # vminsert or balancer
  - '--remoteWrite.url=http://{{ vminsert_container_name }}:8480/insert/0/prometheus'
  # alertmanager
  - '--notifier.url=http://{{ alertmanager_container_name }}:9093/'
  - '--rule=/etc/alerts/*.yml'
  # display source of alerts in grafana
  - '-external.url=http://{{ alertmanager_container_name }}:3000'   # grafana outside container

vmalert_stack_name: victoriametrics
vmalert_swarm_cluster: true
vm_swarm_manager: monitor.openworld.bot
vmalert_swarm_deploy:
  mode: replicated
  replicas: 1
  placement:
    constraints: []

vmalert_templates_include:
  - node_exporter_cpu.yml

vmalert_additional_alerts:
  - filename: xray_anomalies.yml
    data:
      groups:
        - name: xray_anomaly_alerts
          rules:
            - alert: XRayAnomalousUserActivity
              expr: |
                (sum by (country, telegram_id) (xray:user_total_connections_5m:increase) > 2000)
                > on(country) group_left() xray:user_connections_5m:p99_99
                and on(country) (
                  xray:user_connections_5m:p99_99 > 3 * xray:user_connections_5m:p99_5
                )
              for: 15m
              labels:
                severity: warning
                project: akh
                percentile: "99.99"
              annotations:
                summary: !unsafe "👤 [{{ $labels.country }}] {{ $labels.telegram_id }} | {{ $value | humanize }} конн. | p99.99%"
                summary_resolved: !unsafe "{{ $labels.telegram_id }} / {{ $value | humanize }} conn. anomaly is resolved."

            - alert: XRayAnomalousUserActivity
              expr: |
                (sum by (country, telegram_id) (xray:user_total_connections_5m:increase) > 2000)
                > on(country) group_left() xray:user_connections_5m:p99_5
                and on(country) (
                  xray:user_connections_5m:p99_5 > 3 * xray:user_connections_5m:p99
                )
              for: 15m
              labels:
                severity: warning
                project: akh
                percentile: "99.5"
              annotations:
                summary: !unsafe "👤 [{{ $labels.country }}] {{ $labels.telegram_id }} | {{ $value | humanize }} конн. | p99.5%"
                summary_resolved: !unsafe "{{ $labels.telegram_id }} / {{ $value | humanize }} conn. anomaly is resolved."

            - alert: XRayAnomalousUserActivity
              expr: |
                (sum by (country, telegram_id) (xray:user_total_connections_5m:increase) > 2000)
                > on(country) group_left() xray:user_connections_5m:p99
                and on(country) (
                  xray:user_connections_5m:p99 > 3 * xray:user_connections_5m:p95
                )
              for: 15m
              labels:
                severity: warning
                project: akh
                percentile: "99.0"
              annotations:
                summary: !unsafe "👤 [{{ $labels.country }}] {{ $labels.telegram_id }} | {{ $value | humanize }} конн. | p99.0%"
                summary_resolved: !unsafe "{{ $labels.telegram_id }} / {{ $value | humanize }} conn. anomaly is resolved."

            - alert: XRayAnomalousUserActivity
              expr: |
                (sum by (country, telegram_id) (xray:user_total_connections_5m:increase) > 2000)
                > on(country) group_left() xray:user_connections_5m:p95
                and on(country) (
                  xray:user_connections_5m:p95 > 3 * xray:user_connections_5m:p90
                )
              for: 15m
              labels:
                severity: warning
                project: akh
                percentile: "95.0"
              annotations:
                summary: !unsafe "👤 [{{ $labels.country }}] {{ $labels.telegram_id }} | {{ $value | humanize }} конн. | p95.0%"
                summary_resolved: !unsafe "{{ $labels.telegram_id }} / {{ $value | humanize }} conn. anomaly is resolved."